"""add soft delete and versioning support

Revision ID: 10ef1eaa841e
Revises: cfe1b7a7c18b
Create Date: 2026-07-23 13:21:00.674680

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '10ef1eaa841e'
down_revision: Union[str, Sequence[str], None] = 'cfe1b7a7c18b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    op.add_column('gallery_images', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    op.add_column('learning_resources', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    op.add_column('partners', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    op.add_column('projects', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    op.add_column('research_papers', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    op.add_column('team_members', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('team_members', 'is_deleted')
    op.drop_column('research_papers', 'is_deleted')
    op.drop_column('projects', 'is_deleted')
    op.drop_column('partners', 'is_deleted')
    op.drop_column('learning_resources', 'is_deleted')
    op.drop_column('gallery_images', 'is_deleted')
    op.drop_column('events', 'is_deleted')
    # ### end Alembic commands ###
