export const resourceConfigs = {
  slides: {
    title: "Slides",
    endpoint: "/slides",
    idField: "id",
    canCreate: true,
    canUpdate: true,
    canDelete: true,
    listParams: [{ name: "site", label: "Site", default: "main" }],
    fields: [
      { name: "site", label: "Site", type: "text", default: "main", createOnly: true },
      { name: "image_url", label: "Image URL", type: "text", required: true },
      { name: "caption", label: "Caption", type: "textarea" },
      { name: "order", label: "Order", type: "number", default: 0 },
      { name: "is_active", label: "Active", type: "boolean", default: true },
    ],
    columns: ["caption", "order", "is_active", "site"],
  },

  projects: {
    title: "Projects",
    endpoint: "/projects",
    idField: "id",
    canCreate: true,
    canUpdate: true,
    canDelete: true,
    listParams: [{ name: "site", label: "Site", default: "main" }],
    fields: [
      { name: "site", label: "Site", type: "text", default: "main", createOnly: true },
      { name: "title", label: "Title", type: "text", required: true },
      { name: "slug", label: "Slug", type: "text", required: true, createOnly: true },
      { name: "cover_image_url", label: "Cover Image URL", type: "text" },
      { name: "abstract", label: "Abstract", type: "textarea" },
      { name: "description", label: "Description", type: "textarea" },
      { name: "tech_stack", label: "Tech Stack", type: "tags" },
      { name: "github_url", label: "GitHub URL", type: "text" },
      { name: "live_url", label: "Live URL", type: "text" },
      { name: "category_id", label: "Category ID", type: "text" },
      { name: "status", label: "Status", type: "select", options: ["ongoing", "completed", "paused"], default: "ongoing" },
    ],
    columns: ["title", "status", "site"],
  },

  blog: {
    title: "Blog Posts",
    endpoint: "/blog",
    idField: "id",
    canCreate: true,
    canUpdate: true,
    canDelete: true,
    listParams: [{ name: "site", label: "Site", default: "main" }],
    fields: [
      { name: "site", label: "Site", type: "text", default: "main", createOnly: true },
      { name: "title", label: "Title", type: "text", required: true },
      { name: "slug", label: "Slug", type: "text", required: true, createOnly: true },
      { name: "excerpt", label: "Excerpt", type: "textarea" },
      { name: "cover_image_url", label: "Cover Image URL", type: "text" },
      { name: "content", label: "Content", type: "textarea" },
      { name: "author", label: "Author", type: "text" },
      { name: "is_published", label: "Published", type: "boolean", default: true },
      { name: "published_at", label: "Published At", type: "datetime" },
    ],
    columns: ["title", "author", "is_published", "site"],
  },

  categories: {
    title: "Categories",
    endpoint: "/categories",
    idField: "id",
    canCreate: true,
    canUpdate: false,
    canDelete: true,
    listParams: [{ name: "type", label: "Type", default: "" }],
    fields: [
      { name: "name", label: "Name", type: "text", required: true },
      { name: "slug", label: "Slug", type: "text", required: true },
      { name: "type", label: "Type", type: "text", required: true },
      { name: "order", label: "Order", type: "number", default: 0 },
    ],
    columns: ["name", "type", "order"],
  },

  "core-values": {
    title: "Core Values",
    endpoint: "/core-values",
    idField: "id",
    canCreate: true,
    canUpdate: true,
    canDelete: true,
    listParams: [{ name: "site", label: "Site", default: "main" }],
    fields: [
      { name: "site", label: "Site", type: "text", default: "main", createOnly: true },
      { name: "title", label: "Title", type: "text", required: true },
      { name: "description", label: "Description", type: "textarea" },
      { name: "icon_name", label: "Icon Name", type: "text", default: "Sparkles" },
      { name: "order", label: "Order", type: "number", default: 0 },
    ],
    columns: ["title", "icon_name", "order", "site"],
  },

  events: {
    title: "Events",
    endpoint: "/events",
    idField: "id",
    canCreate: true,
    canUpdate: true,
    canDelete: true,
    listParams: [{ name: "site", label: "Site", default: "main" }],
    fields: [
      { name: "site", label: "Site", type: "text", default: "main", createOnly: true },
      { name: "title", label: "Title", type: "text", required: true },
      { name: "description", label: "Description", type: "textarea" },
      { name: "banner_url", label: "Banner URL", type: "text" },
      { name: "event_date", label: "Event Date", type: "datetime", required: true },
      { name: "is_past", label: "Past Event", type: "boolean", default: false },
    ],
    columns: ["title", "event_date", "is_past", "site"],
  },

  team: {
    title: "Team Members",
    endpoint: "/team",
    idField: "id",
    canCreate: true,
    canUpdate: true,
    canDelete: true,
    listParams: [
      { name: "site", label: "Site", default: "main" },
      { name: "year", label: "Year", default: "" },
    ],
    fields: [
      { name: "site", label: "Site", type: "text", default: "main", createOnly: true },
      { name: "name", label: "Name", type: "text", required: true },
      { name: "role", label: "Role", type: "text", required: true },
      { name: "bio", label: "Bio", type: "textarea" },
      { name: "photo_url", label: "Photo URL", type: "text" },
      { name: "year", label: "Year", type: "number", required: true },
      { name: "linkedin_url", label: "LinkedIn URL", type: "text" },
      { name: "twitter_url", label: "Twitter URL", type: "text" },
      { name: "is_alumni_active", label: "Alumni Active", type: "boolean", default: false },
    ],
    columns: ["name", "role", "year", "site"],
  },

  gallery: {
    title: "Gallery",
    endpoint: "/gallery",
    idField: "id",
    canCreate: true,
    canUpdate: true,
    canDelete: true,
    listParams: [{ name: "event_id", label: "Event ID", default: "" }],
    fields: [
      {
        name: "event_id",
        label: "Event",
        type: "async-select",
        required: true,
        endpoint: "/events/",
        endpointParams: { site: "indabax", limit: 100 },
        optionValue: "id",
        optionLabel: "title",
      },
      { name: "image_url", label: "Image URL", type: "text", required: true },
      { name: "caption", label: "Caption", type: "text" },
    ],
    columns: ["image_url", "event_id"],
  },

  research: {
    title: "Research Papers",
    endpoint: "/research-papers",
    idField: "id",
    canCreate: true,
    canUpdate: false,
    canDelete: true,
    listParams: [
      { name: "category", label: "Category", default: "" },
      { name: "year", label: "Year", default: "" },
    ],
    fields: [
      { name: "site", label: "Site", type: "text", default: "main" },
      { name: "title", label: "Title", type: "text", required: true },
      { name: "authors", label: "Authors", type: "text", required: true },
      { name: "abstract", label: "Abstract", type: "textarea" },
      { name: "category_id", label: "Category ID", type: "text" },
      { name: "year", label: "Year", type: "text" },
      { name: "pdf_url", label: "PDF URL", type: "text", required: true },
    ],
    columns: ["title", "authors", "year"],
  },
};
